# Generated by Django 2.1.1 on 2019-09-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='trans_type',
            field=models.CharField(choices=[('Outgoing', 'Outgoing'), ('Transfer', 'Transfer'), ('Direct Transfer', 'Direct Transfer')], max_length=50, verbose_name='Type'),
        ),
    ]
