# Generated by Django 2.1.1 on 2019-09-10 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190906_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='trans_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
