# Generated by Django 2.1.1 on 2019-09-10 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20190910_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='trans_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
