# Generated by Django 2.1.1 on 2019-09-11 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20190910_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='attachment',
            field=models.FileField(blank=True, default='None', upload_to='incoming_form', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='project_site',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_project_site', to='workforce.ProjectSite'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='trans_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
