# Generated by Django 2.1.1 on 2019-09-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20190911_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='attachment',
            field=models.FileField(blank=True, default='None', upload_to='incoming_form', verbose_name='Form'),
        ),
    ]
