# Generated by Django 2.1.1 on 2019-11-25 20:32

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20190911_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='attachment',
            field=models.FileField(blank=True, upload_to='incoming_form', validators=[warehouse.models.validate_upload_size], verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='attachment',
            field=models.FileField(blank=True, upload_to='incoming_form', validators=[warehouse.models.validate_upload_size], verbose_name='Form'),
        ),
    ]
