# Generated by Django 2.1.1 on 2020-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20191126_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='status',
            field=models.CharField(choices=[('For Verification', 'For Verification'), ('Verified', 'Verified')], default='For Verification', max_length=200, verbose_name='Status'),
        ),
    ]
