# Generated by Django 2.1.1 on 2020-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_outgoing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='work_item',
            field=models.CharField(choices=[('1', 'Work Item 1'), ('2', 'Work Item 2')], default='Ask Engineer', max_length=200, verbose_name='Work Item'),
        ),
    ]
