# Generated by Django 2.1.1 on 2020-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_outgoing_work_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoing',
            name='work_item',
            field=models.CharField(choices=[('1', 'Active Protection System'), ('2', 'Active Wire Mesh System (High Tensile)'), ('3', 'Aggregate Subbase Course'), ('4', 'Chevron Signs (450mm X 600mm)'), ('5', 'Concrete (Slope Protection)'), ('6', 'Concrete Curb (Cast in Place)'), ('7', 'Concrete Gutter, Cast in Place'), ('8', 'Concrete Railing (Standard)'), ('9', 'Curb and gutter, cast-in-place'), ('10', 'Danger/Warning Signs (60 cm Triangle) W1-3'), ('11', 'Detour/ Access Road'), ('12', 'Drain Pipe (Galvanized)'), ('13', 'Drain Pipe (PVC)'), ('14', 'Elastomeric Bearing Pad'), ('15', 'Erosion Control Mat (Type 4)')], default='Ask Engineer', max_length=200, verbose_name='Work Item'),
        ),
    ]
