# Generated by Django 2.1.1 on 2020-06-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20200615_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing',
            name='work_item',
        ),
    ]
