# Generated by Django 2.1.1 on 2020-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_outgoing_item_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='track_no',
            field=models.PositiveIntegerField(default=0, verbose_name='Tracking No'),
        ),
    ]
