# Generated by Django 2.1.1 on 2020-06-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_incoming_track_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming',
            name='track_no',
        ),
    ]
