# Generated by Django 2.1.1 on 2020-06-22 08:35

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_remove_incoming_track_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='attachment',
            field=models.FileField(blank=True, upload_to='incoming_form', validators=[warehouse.models.validate_upload_size], verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='attachment',
            field=models.FileField(blank=True, upload_to='incoming_form', validators=[warehouse.models.validate_upload_size], verbose_name='Form'),
        ),
    ]
