# Generated by Django 2.1.15 on 2021-03-25 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0019_auto_20210325_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
