# Generated by Django 2.1.1 on 2018-11-26 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=200, verbose_name='Item No')),
                ('description', models.CharField(max_length=200, verbose_name='Item Description')),
                ('unit', models.CharField(max_length=200, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='OperationalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('category', models.CharField(choices=[('DPWH', 'DPWH'), ('Contractor', 'Contractor')], max_length=200, verbose_name='Category')),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Cost')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Operational Cost',
                'verbose_name_plural': 'Operational Cost',
            },
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('work_accomplished', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Work Done (%)')),
                ('activity', models.TextField(verbose_name='Activity Details')),
                ('issues', models.TextField(verbose_name='Issues')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Document')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(choices=[('DPWH', 'DPWH'), ('Contractor', 'Contractor')], max_length=200, verbose_name='Office')),
                ('title', models.CharField(choices=[('Project Engineer', 'Project Engineer'), ('Resident Engineer', 'Resident Engineer'), ('Project Facilitator', 'Project Facilitator'), ('Geodetic Engineer', 'Geodetic Engineer'), ('Office Engineer', 'Office Engineer'), ('Regional Technical Engineer', 'Regional Technical Engineer')], max_length=200, verbose_name='Title')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=40, verbose_name='Project Code')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('project_detail', models.TextField(verbose_name='Details')),
                ('project_pic', models.ImageField(default='profile_pic/default.png', upload_to='project_pic', verbose_name='Project Profile')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='base_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='operation.Project'),
        ),
        migrations.AddField(
            model_name='operationalstatus',
            name='base_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_status', to='operation.Project'),
        ),
        migrations.AddField(
            model_name='operationalcost',
            name='base_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_cost', to='operation.Project'),
        ),
    ]
