# Generated by Django 2.1.1 on 2018-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('For Bidding', 'For Bidding'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed')], default='Completed', max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operationalcost',
            name='category',
            field=models.CharField(choices=[('Construction Materials', 'Construction Materials'), ('Labor', 'Labor')], max_length=200, verbose_name='Category'),
        ),
    ]
