# Generated by Django 2.1.1 on 2018-11-27 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181126_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200, verbose_name='Project ID')),
                ('award_date', models.DateField(default=django.utils.timezone.now, verbose_name='Notice of Award Date')),
                ('proceed_date', models.DateField(default=django.utils.timezone.now, verbose_name='Notice to Proceed Date')),
                ('effectivity_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effectivity Date')),
                ('expiry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date')),
                ('contract_duration', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Contract Cost')),
                ('contract_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Contract Cost')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
            },
        ),
    ]
