# Generated by Django 2.1.1 on 2018-11-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='contract_duration',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Contract Duration'),
        ),
    ]
