# Generated by Django 2.1.1 on 2018-11-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20181127_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpercentage',
            name='work_type',
            field=models.CharField(choices=[('As Planned', 'As Planned'), ('Actual', 'Actual')], default='Actual', max_length=200, verbose_name='Type'),
        ),
    ]
