# Generated by Django 2.1.1 on 2018-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20181127_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpercentage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='workpercentage',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='workpercentage',
            name='work_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type'),
        ),
    ]
