# Generated by Django 2.1.1 on 2018-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_auto_20181127_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpercentage',
            name='work_type',
            field=models.CharField(blank=True, choices=[('As Planned', 'As Planned'), ('Actual', 'Actual')], max_length=200, null=True, verbose_name='Type'),
        ),
    ]
