# Generated by Django 2.1.1 on 2018-11-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20181127_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpercentage',
            name='work_type',
        ),
    ]
