# Generated by Django 2.1.1 on 2018-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_remove_workpercentage_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpercentage',
            name='value2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='As Planned'),
        ),
        migrations.AlterField(
            model_name='workpercentage',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual'),
        ),
    ]
