# Generated by Django 2.1.1 on 2018-11-27 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20181127_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='As Planned')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='operation.Project')),
            ],
            options={
                'verbose_name': 'As Planned Data',
                'verbose_name_plural': 'As Planned Data',
            },
        ),
        migrations.AlterModelOptions(
            name='actualwork',
            options={'verbose_name': 'Actual Data', 'verbose_name_plural': 'Actual Data'},
        ),
        migrations.AlterField(
            model_name='actualwork',
            name='base_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='operation.Project'),
        ),
        migrations.AlterField(
            model_name='actualwork',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual Value'),
        ),
    ]
