# Generated by Django 2.1.1 on 2018-11-27 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20181127_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('materials', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Materials')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_expense', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Major Expense',
                'verbose_name_plural': 'Major Expense',
            },
        ),
    ]
