# Generated by Django 2.1.1 on 2018-11-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_auto_20181127_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorexpense',
            name='labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Labor'),
        ),
        migrations.AddField(
            model_name='majorexpense',
            name='others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Others'),
        ),
        migrations.AddField(
            model_name='majorexpense',
            name='overhead',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Overhead'),
        ),
        migrations.AlterField(
            model_name='majorexpense',
            name='materials',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Construction Materials'),
        ),
    ]
