# Generated by Django 2.1.1 on 2018-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_auto_20181127_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalstatus',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Document'),
        ),
    ]
