# Generated by Django 2.1.1 on 2018-12-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_auto_20181127_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationalStatus',
            new_name='Report',
        ),
    ]
