# Generated by Django 2.1.1 on 2018-12-11 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_auto_20181211_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('caption', models.TextField(verbose_name='Caption')),
                ('image', models.ImageField(default='profile_pic/default.png', upload_to='project_images', verbose_name='Project Profile')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
