# Generated by Django 2.1.1 on 2018-12-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0020_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='caption',
        ),
    ]
