# Generated by Django 2.1.1 on 2018-12-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_auto_20181212_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorexpense',
            name='base_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_expense', to='operation.Project'),
        ),
    ]
