# Generated by Django 2.1.1 on 2019-01-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_auto_20181214_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='detail',
            field=models.TextField(default='Details here...', verbose_name='Details'),
        ),
    ]
