# Generated by Django 2.1.1 on 2019-01-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0027_gallery_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-date'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
