# Generated by Django 2.1.1 on 2019-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_report_slippage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weather',
            field=models.CharField(default='Weather Condition...', max_length=200, verbose_name='Weather Condition'),
        ),
    ]
