# Generated by Django 2.1.1 on 2019-01-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0031_auto_20190128_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorexpense',
            options={'get_latest_by': 'date', 'verbose_name': 'Major Expense', 'verbose_name_plural': 'Major Expense'},
        ),
    ]
