# Generated by Django 2.1.1 on 2019-01-28 16:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_auto_20190128_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Billing')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount')),
                ('document', models.FileField(blank=True, null=True, upload_to='billing_docs', verbose_name='Billing Document')),
                ('status', models.CharField(choices=[('On-Going', 'On-Going'), ('Billing Complete', 'Billing Complete')], max_length=200, verbose_name='Status')),
                ('image', models.ImageField(default='profile_pic/default.png', upload_to='billing_checks', verbose_name='Cheque')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'ordering': ['-date'],
            },
        ),
    ]
