# Generated by Django 2.1.1 on 2019-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0033_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='billing_docs/', verbose_name='Billing Document'),
        ),
    ]
