# Generated by Django 2.1.1 on 2019-01-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_auto_20190129_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('For Billing', 'For Billing'), ('On-Process', 'On-Process'), ('Completed', 'Completed')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='title',
            field=models.CharField(choices=[('Project Engineer', 'Project Engineer'), ('Resident Engineer', 'Resident Engineer'), ('Project Facilitator', 'Project Facilitator'), ('Geodetic Engineer', 'Geodetic Engineer'), ('Office Engineer', 'Office Engineer'), ('Regional Technical Engineer', 'Regional Technical Engineer')], max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('On-Process', 'On-Process'), ('For Billing', 'For Billing'), ('Completed', 'Completed')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='weather',
            field=models.CharField(choices=[('Sunny', 'Sunny'), ('Cloudy', 'Cloudy'), ('Rain', 'Rain'), ('Windy', 'Windy'), ('Stormy', 'Stormy')], max_length=200, verbose_name='Weather Condition'),
        ),
    ]
