# Generated by Django 2.1.1 on 2019-01-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0036_auto_20190129_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('On-Process', 'On-Process'), ('For Billing', 'For Billing'), ('Completed', 'Completed')], default='Under Construction', max_length=200, verbose_name='Status'),
        ),
    ]
