# Generated by Django 2.1.1 on 2019-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0038_auto_20190129_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='detail',
            field=models.TextField(default='Details here...', verbose_name='Details'),
        ),
    ]
