# Generated by Django 2.1.1 on 2019-03-23 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0039_billing_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('detail', models.TextField(default='Details here...', verbose_name='Details')),
                ('image', models.ImageField(blank=True, default=' ', upload_to='project_images', verbose_name='Project Profile')),
                ('base_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_slides', to='operation.Gallery')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
                'ordering': ['-date'],
            },
        ),
    ]
