# Generated by Django 2.1.1 on 2019-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0041_remove_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='detail',
            field=models.CharField(max_length=500, verbose_name='Details'),
        ),
    ]
