# Generated by Django 2.1.1 on 2019-06-13 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0042_auto_20190323_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('planned', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Planned Value')),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual Value')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Work Stat',
                'verbose_name_plural': 'Work Stat',
            },
        ),
    ]
