# Generated by Django 2.1.1 on 2019-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0044_auto_20190613_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=0, max_length=200, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
