# Generated by Django 2.1.1 on 2019-06-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0045_auto_20190613_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount')),
                ('actual_work', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Work Done (%)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='operation.Item')),
            ],
            options={
                'verbose_name': 'Project Item',
                'verbose_name_plural': 'Project Items',
            },
        ),
    ]
