# Generated by Django 2.1.1 on 2019-06-13 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0046_projectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
