# Generated by Django 2.1.1 on 2019-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0048_projectitem_base_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Part A', 'Facilities for Engineers'), ('Part B', 'Other General Requirements'), ('Part C', 'Earth Works'), ('Part D', 'Sub Base and Base Course'), ('Part E', 'Surface Course'), ('Part G', 'Drainage and Slope Protection'), ('Part H', 'Miscellaneous')], max_length=200, verbose_name='Category'),
        ),
    ]
