# Generated by Django 2.1.1 on 2019-06-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0050_auto_20190613_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='planned_work',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Weighted %'),
        ),
    ]
