# Generated by Django 2.1.1 on 2019-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0051_projectitem_planned_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexpense',
            name='labor',
        ),
        migrations.RemoveField(
            model_name='majorexpense',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='majorexpense',
            name='others',
        ),
        migrations.RemoveField(
            model_name='majorexpense',
            name='overhead',
        ),
        migrations.AddField(
            model_name='majorexpense',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='majorexpense',
            name='spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Spending'),
        ),
    ]
