# Generated by Django 2.1.1 on 2019-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0053_majorexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, upload_to='project_pic', verbose_name='Project Profile'),
        ),
    ]
