# Generated by Django 2.1.1 on 2019-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0055_auto_20190614_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='license',
            field=models.CharField(choices=[('AIP', 'AIP'), ('BMK', 'BMK'), ('BMK/AIP', 'BMK/AIP')], default='AIP', max_length=200, verbose_name='License'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.TextField(verbose_name='Contract Name'),
        ),
    ]
