# Generated by Django 2.1.1 on 2019-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0056_auto_20190614_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='implementing_office',
            field=models.CharField(choices=[('DPWH-CAR', 'DPWH-CAR'), ('DPWH-REGION I', 'DPWH-REGION I'), ('DPWH-REGION II', 'DPWH-REGION II'), ('DPWH-MPFDEO', 'DPWH-MPFDEO'), ('DPWH-BFDEO', 'DPWH-BFDEO'), ('DPWH-IS2DEO', 'DPWH-IS2DEO'), ('LGU-SAN EMILIO', 'LGU-SAN EMILIO'), ('LGU-BONTOC', 'LGU-BONTOC')], default='DPWH-CAR', max_length=200, verbose_name='Implementing Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='time_extension',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Time Extension (Days)'),
        ),
    ]
