# Generated by Django 2.1.1 on 2019-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0057_auto_20190614_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='office',
            field=models.CharField(choices=[('Bidding', 'Bidding'), ('On-Site', 'On-Site')], max_length=200, verbose_name='Specifics'),
        ),
    ]
