# Generated by Django 2.1.1 on 2019-06-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0059_auto_20190614_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='detail',
        ),
    ]
