# Generated by Django 2.1.1 on 2019-06-14 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0060_remove_billing_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Deposited'),
        ),
    ]
