# Generated by Django 2.1.1 on 2019-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0061_auto_20190614_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstat',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AlterField(
            model_name='majorexpense',
            name='category',
            field=models.CharField(choices=[('Cement', 'Cement'), ('Labor', 'Labor'), ('Fuel', 'Fuel'), ('General & Admin', 'General & Admin'), ('Materials', 'Materials'), ('Overhead', 'Overhead'), ('Equipment', 'Equipment')], max_length=200, verbose_name='Category'),
        ),
    ]
