# Generated by Django 2.1.1 on 2019-07-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0063_auto_20190717_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstat',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
