# Generated by Django 2.1.1 on 2019-07-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0065_remove_workstat_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstat',
            old_name='date_start',
            new_name='date',
        ),
    ]
