# Generated by Django 2.1.1 on 2019-07-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0066_auto_20190717_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstat',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
