# Generated by Django 2.1.1 on 2019-07-17 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0067_auto_20190717_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='sequence',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
