# Generated by Django 2.1.1 on 2019-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0068_auto_20190717_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='sequence',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Sequence'),
        ),
    ]
