# Generated by Django 2.1.1 on 2019-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0069_auto_20190718_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='dependency',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Dependency'),
        ),
    ]
