# Generated by Django 2.1.1 on 2019-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0071_auto_20190724_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorexpense',
            name='category',
        ),
        migrations.AddField(
            model_name='majorexpense',
            name='document',
            field=models.FileField(default=' ', upload_to='major_expense/', verbose_name='Document'),
        ),
    ]
