# Generated by Django 2.1.1 on 2019-08-29 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0073_auto_20190724_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('Project Log Sheet', 'Project Log Sheet'), ('Statement of Work Accomplished', 'Statement of Work Accomplished'), ('Straight Line Diagram', 'Straight Line Diagram'), ('Geotagged Pictures', 'Geotagged Pictures')], max_length=200, verbose_name='Type')),
                ('document', models.FileField(blank=True, null=True, upload_to='reports_docs/', verbose_name='Upload Report')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='operation.Project')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['-date'],
            },
        ),
    ]
