# Generated by Django 2.1.1 on 2019-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0074_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='remarks',
            field=models.TextField(default='Remarks...', verbose_name='Remarks'),
        ),
    ]
