# Generated by Django 2.1.1 on 2019-08-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0077_auto_20190830_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporting',
            old_name='type',
            new_name='report_type',
        ),
        migrations.AlterField(
            model_name='reporting',
            name='document',
            field=models.FileField(blank=True, default='', upload_to='reports_docs/', verbose_name='Upload Report'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Remarks'),
        ),
    ]
