# Generated by Django 2.1.1 on 2019-09-06 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0079_auto_20190830_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstat',
            name='slippage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actual Value'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='_____Date of End_____'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='_____Date of Start_____'),
        ),
    ]
