# Generated by Django 2.1.1 on 2019-09-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0083_auto_20190906_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='document',
        ),
        migrations.RemoveField(
            model_name='report',
            name='slippage',
        ),
        migrations.RemoveField(
            model_name='report',
            name='work_accomplished',
        ),
    ]
