# Generated by Django 2.1.1 on 2019-09-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0084_auto_20190906_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Facilities for Engineers', 'Facilities for Engineers'), ('Other General Requirements', 'Other General Requirements'), ('Earth Works', 'Earth Works'), ('Sub Base and Base Course', 'Sub Base and Base Course'), ('Surface Course', 'Surface Course'), ('Drainage and Slope Protection', 'Drainage and Slope Protection'), ('Miscellaneous', 'Miscellaneous'), ('Bridge Construction', 'Bridge Construction'), ('Water Supply', 'Water Supply')], max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='report_type',
            field=models.CharField(choices=[('Project Log Sheet', 'Project Log Sheet'), ('Statement of Work Accomplished', 'Statement of Work Accomplished'), ('Straight Line Diagram', 'Straight Line Diagram'), ('Geotagged Pictures', 'Geotagged Pictures'), ('Project Monitor', 'Project Monitor')], max_length=200, verbose_name='Type'),
        ),
    ]
