# Generated by Django 2.1.1 on 2019-09-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0085_auto_20190907_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='actual_work',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Work Done (%)'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='planned_work',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Weighted %'),
        ),
        migrations.AlterField(
            model_name='workstat',
            name='actual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Actual Value'),
        ),
        migrations.AlterField(
            model_name='workstat',
            name='planned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Planned Value'),
        ),
        migrations.AlterField(
            model_name='workstat',
            name='slippage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Slippage'),
        ),
    ]
