# Generated by Django 2.1.1 on 2020-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0088_auto_20190910_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='implementing_office',
            field=models.CharField(choices=[('DPWH-CAR', 'DPWH-CAR'), ('DPWH-REGION I', 'DPWH-REGION I'), ('DPWH-REGION II', 'DPWH-REGION II'), ('DPWH-MPFDEO', 'DPWH-MPFDEO'), ('DPWH-BFDEO', 'DPWH-BFDEO'), ('DPWH-IS2DEO', 'DPWH-IS2DEO'), ('LGU-SAN EMILIO', 'LGU-SAN EMILIO'), ('LGU-BONTOC', 'LGU-BONTOC'), ('ALTENERGY', 'ALTENERGY')], max_length=200, verbose_name='Implementing Office'),
        ),
    ]
