# Generated by Django 2.1.1 on 2020-02-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0091_auto_20200223_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstat',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Actual Value'),
        ),
    ]
