# Generated by Django 2.1.1 on 2020-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0092_auto_20200223_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstat',
            name='slippage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Slippage'),
        ),
    ]
