# Generated by Django 2.1.1 on 2019-09-03 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0062_auto_20190815_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200, verbose_name='Title')),
                ('document_type', models.CharField(choices=[('OR', 'OR'), ('CR', 'CR'), ('Deed of Sale', 'Deed of Sale'), ('Certificate', 'Certificate'), ('Violations', 'Violations')], max_length=200, verbose_name='Document Type')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('expiry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date')),
                ('doc_file', models.FileField(blank=True, default='profile_pic/default.png', upload_to='unit_files', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_no', models.CharField(default='None', max_length=200, verbose_name='JO No.')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Date')),
                ('smr', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR')),
                ('kmr', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR')),
                ('detail', models.TextField(verbose_name='Job Request Details')),
                ('status', models.CharField(choices=[('For Approval', 'For Approval'), ('Under Repair', 'Under Repair'), ('Finished', 'Finished')], default='For Approval', max_length=200, verbose_name='Status')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Job Order Request',
                'verbose_name_plural': 'Job Order Request',
            },
        ),
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=200, verbose_name='Details of Work Done')),
            ],
            options={
                'verbose_name': 'Manpower',
                'verbose_name_plural': 'Manpower',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='From')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('slide_pic', models.ImageField(default='', upload_to='unit_pic', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='From')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='To')),
                ('note', models.CharField(max_length=500, verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travel',
            },
        ),
        migrations.CreateModel(
            name='UnitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_no', models.CharField(max_length=200, verbose_name='Body No')),
                ('plate_no', models.CharField(default='No Plate', max_length=200, verbose_name='Plate No')),
                ('unit_type', models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('BD', 'BD'), ('CC', 'CC'), ('CCT', 'CCT'), ('CP', 'CP'), ('CT', 'CT'), ('DT', 'DT'), ('FT', 'FT'), ('GS', 'GS'), ('HBT', 'HBT'), ('HE', 'HE'), ('LBT', 'LBT'), ('MC', 'MC'), ('MG', 'MG'), ('MT', 'MT'), ('SL', 'SL'), ('SLT', 'SLT'), ('SV', 'SV'), ('TC', 'TC'), ('TH', 'TH'), ('VC', 'VC'), ('VD', 'VD'), ('WL', 'WL'), ('TL', 'TL'), ('AC', 'AC'), ('WG', 'WG')], default='Uncategorized', max_length=200, verbose_name='Unit Type')),
                ('unit_desc', models.CharField(max_length=500, verbose_name='Unit Description')),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Idle', 'Idle'), ('Under Repair', 'Under Repair'), ('For Disposal', 'For Disposal')], max_length=200, verbose_name='Status')),
                ('profile_pic', models.ImageField(default='profile_pic/default.png', upload_to='unit_pic', verbose_name='Unit Pic')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('engine_no', models.CharField(default=0, max_length=200, verbose_name='Engine No')),
                ('chassis_no', models.CharField(default=0, max_length=200, verbose_name='Chassis No')),
                ('net_capacity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Net Capacity.')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Price')),
                ('cr', models.CharField(blank=True, max_length=200, null=True, verbose_name='CR')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='workforce.BasicProfile')),
                ('project_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_site', to='workforce.ProjectSite')),
                ('registered_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='workforce.BasicProfile')),
            ],
            options={
                'verbose_name': 'Unit Profile',
                'verbose_name_plural': 'Unit Profile',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Started')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Est. Date of Accomplishment')),
                ('service_type', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Unscheduled', 'Unscheduled'), ('PMS', 'PMS'), ('Capital Repair', 'Capital Repair')], max_length=200, verbose_name='Type of Service')),
                ('repair_cause', models.CharField(choices=[('Mishandling', 'Mishandling'), ('Wear & Tear', 'Wear & Tear'), ('Back Job', 'Back Job'), ('Others', 'Others')], max_length=200, verbose_name='Cause of Repair')),
                ('scope_work', models.TextField(default='Enter the scope of work to be done', verbose_name='Scope of Work')),
                ('work_done', models.TextField(verbose_name='Details of Work Done')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('wo_status', models.CharField(choices=[('For Approval', 'For Approval'), ('Under Repair', 'Under Repair'), ('Finished', 'Finished')], default='Under Repair', max_length=200, verbose_name='Status')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('base_jo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='fleet.JobOrder')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
            },
        ),
        migrations.AddField(
            model_name='travel',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_history', to='fleet.UnitProfile'),
        ),
        migrations.AddField(
            model_name='travel',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_operator', to='workforce.BasicProfile'),
        ),
        migrations.AddField(
            model_name='slides',
            name='base_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_images', to='fleet.UnitProfile'),
        ),
        migrations.AddField(
            model_name='operator',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_history', to='fleet.UnitProfile'),
        ),
        migrations.AddField(
            model_name='operator',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_operator', to='workforce.BasicProfile'),
        ),
        migrations.AddField(
            model_name='manpower',
            name='base_wo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower', to='fleet.WorkOrder'),
        ),
        migrations.AddField(
            model_name='manpower',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manpower', to='workforce.BasicProfile'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='base_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_unit', to='fleet.UnitProfile'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='request_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_by', to='workforce.BasicProfile'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jo_location', to='workforce.ProjectSite'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='base_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_files', to='fleet.UnitProfile'),
        ),
    ]
