# Generated by Django 2.1.1 on 2019-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='jo_pic',
            field=models.ImageField(blank=True, upload_to='jo_pic', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_pic',
            field=models.ImageField(blank=True, upload_to='wo_pic', verbose_name='Image'),
        ),
    ]
