# Generated by Django 2.1.1 on 2019-11-22 14:21

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_auto_20191114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joimage',
            name='jo_pic',
            field=models.ImageField(blank=True, upload_to='jo_pic', validators=[fleet.models.validate_upload_size], verbose_name='Image'),
        ),
    ]
