# Generated by Django 2.1.1 on 2019-11-24 20:33

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20191122_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='slide_pic',
            field=models.ImageField(default='', upload_to='unit_pic', validators=[fleet.models.validate_upload_size], verbose_name='Image'),
        ),
    ]
