# Generated by Django 2.1.1 on 2019-11-25 20:40

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20191124_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='unit_files', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='slide_pic',
            field=models.ImageField(blank=True, upload_to='unit_pic', validators=[fleet.models.validate_upload_size], verbose_name='Image'),
        ),
    ]
