# Generated by Django 2.1.1 on 2019-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_auto_20191125_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(blank=True, default='', upload_to='unit_files', verbose_name='Document'),
        ),
    ]
