# Generated by Django 2.1.1 on 2019-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_auto_20191127_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Under Repair', 'Under Repair'), ('Sustained', 'Sustained'), ('Finished', 'Finished')], default='For Approval', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='unitprofile',
            name='status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Idle', 'Idle'), ('Under Repair', 'Under Repair'), ('For Disposal', 'For Disposal'), ('Sustained', 'Sustained')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_status',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Under Repair', 'Under Repair'), ('Sustained', 'Sustained'), ('Finished', 'Finished')], default='Under Repair', max_length=200, verbose_name='Status'),
        ),
    ]
