# Generated by Django 2.1.1 on 2020-01-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_auto_20191205_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='repair_cause',
            field=models.CharField(choices=[('Mishandling', 'Mishandling'), ('Wear & Tear', 'Wear & Tear'), ('Back Job', 'Back Job'), ('Electrical Issues', 'Electrical Issues'), ('PMS', 'PMS'), ('Others', 'Others')], max_length=200, verbose_name='Cause of Repair'),
        ),
    ]
