# Generated by Django 2.1.1 on 2020-02-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_auto_20200122_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='remarks',
            field=models.CharField(default='', max_length=200, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('Documents', 'Documents'), ('Processing', 'Processing'), ('Renewed', 'Renewed')], default='', max_length=50, verbose_name='Status'),
        ),
    ]
