# Generated by Django 2.1.1 on 2020-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='remarks',
            field=models.CharField(default='Notes here', max_length=200, verbose_name='Remarks'),
        ),
    ]
