# Generated by Django 2.1.1 on 2020-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('For Pick-Up', 'For Pick-Up'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='For Pick-Up', max_length=50, verbose_name='Status'),
        ),
    ]
