# Generated by Django 2.1.1 on 2020-02-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_auto_20200224_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='remarks',
            field=models.TextField(verbose_name='Details'),
        ),
    ]
