# Generated by Django 2.1.1 on 2020-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_auto_20200224_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='description',
            field=models.CharField(default=' ', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('For Pick-Up', 'For Pick-Up'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Received', 'Received')], default='For Pick-Up', max_length=50, verbose_name='Status'),
        ),
    ]
