# Generated by Django 2.1.1 on 2020-04-20 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_auto_20200228_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('employee_id', models.CharField(max_length=40, verbose_name='ID No.')),
                ('unit_id', models.CharField(max_length=50, verbose_name='Body No')),
                ('smr_start', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR Start')),
                ('smr_end', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR End')),
                ('kmr_start', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR Start')),
                ('kmr_end', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR End')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('start_hour', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Start')),
                ('end_hour', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='End')),
                ('activity', models.CharField(max_length=40, verbose_name='Activity')),
                ('material', models.CharField(blank=True, max_length=40, verbose_name='Material')),
                ('load', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Load')),
                ('operator', models.CharField(max_length=40, verbose_name='Operator')),
                ('project_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ur_unit', to='fleet.UnitProfile')),
            ],
            options={
                'verbose_name': 'Utilization Report',
                'verbose_name_plural': 'Utilization Reports',
            },
        ),
    ]
