# Generated by Django 2.1.1 on 2020-04-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_utilizationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='project_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ur_site', to='workforce.ProjectSite'),
        ),
    ]
