# Generated by Django 2.1.1 on 2020-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_auto_20200420_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='project_site',
            field=models.CharField(default=None, max_length=100, verbose_name='Project Site'),
            preserve_default=False,
        ),
    ]
