# Generated by Django 2.1.1 on 2020-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_auto_20200420_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizationreport',
            name='unit_type',
            field=models.CharField(default=None, max_length=50, verbose_name='Unit Type'),
            preserve_default=False,
        ),
    ]
