# Generated by Django 2.1.1 on 2020-04-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_utilizationreport_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='kmr_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='KMR End'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='kmr_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='KMR Start'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Load'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='smr_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='SMR End'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='smr_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='SMR Start'),
        ),
    ]
