# Generated by Django 2.1.1 on 2020-04-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_auto_20200420_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='kmr_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR End'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='kmr_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR Start'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='load',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Load'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='smr_end',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR End'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='smr_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR Start'),
        ),
    ]
