# Generated by Django 2.1.1 on 2020-04-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0032_auto_20200420_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizationreport',
            name='twh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='TWH'),
        ),
    ]
