# Generated by Django 2.1.1 on 2020-04-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0033_utilizationreport_twh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationreport',
            name='end_hour',
            field=models.CharField(max_length=50, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='utilizationreport',
            name='start_hour',
            field=models.CharField(max_length=50, verbose_name='Start'),
        ),
    ]
