# Generated by Django 2.1.1 on 2021-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_auto_20210302_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
