# Generated by Django 2.1.1 on 2021-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_auto_20210302_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
