# Generated by Django 2.1.1 on 2021-03-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_auto_20210302_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_dest', to='workforce.ProjectSite'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_source', to='workforce.ProjectSite'),
        ),
    ]
