# Generated by Django 2.1.15 on 2021-03-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_auto_20210306_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='returning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Travel Booked', 'Travel Booked'), ('On its way', 'On its way'), ('Arrived', 'Arrived'), ('Coming back', 'Coming back'), ('Returned', 'Returned'), ('Canceled', 'Canceled')], default='Travel Booked', max_length=50, verbose_name='Status'),
        ),
    ]
