# Generated by Django 2.1.15 on 2021-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_auto_20210306_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='trip',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Two Way', 'Two Way')], default='Two Way', max_length=50, verbose_name='Trip'),
            preserve_default=False,
        ),
    ]
