# Generated by Django 2.1.15 on 2021-03-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0077_subcon_project_site'),
        ('fleet', '0044_travel_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.BasicProfile'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='trip',
            field=models.CharField(choices=[('One Way', 'One Way (Mabayag nga agsubli)'), ('Two Way', 'Two Way (Balikan)')], max_length=50, verbose_name='Trip'),
        ),
    ]
