# Generated by Django 2.1.15 on 2021-03-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0046_auto_20210330_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workforce.BasicProfile'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(blank=True, choices=[('For Approval', 'For Approval'), ('Scheduled', 'Scheduled'), ('Travel Booked', 'Travel Booked'), ('On its way', 'On its way'), ('Arrived', 'Arrived'), ('Coming back', 'Coming back'), ('Returned', 'Returned'), ('Canceled', 'Canceled')], default='For Approval', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
