# Generated by Django 2.1.1 on 2018-10-13 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('mname', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, verbose_name='Gender')),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Ba-ak', 'Ba-ak')], max_length=200, verbose_name='Civil Status')),
                ('religion', models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Pagano', 'Pagano')], max_length=200, verbose_name='Religion')),
                ('dbirth', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('mobile', models.IntegerField(verbose_name='Mobile No.')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('home_address', models.CharField(max_length=1000, verbose_name='Home Address')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic', verbose_name='Profile Pic')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Engr.', 'Engr.'), ('Arch.', 'Arch.')], max_length=200, verbose_name='Title')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Basic Profile',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
