# Generated by Django 2.1.1 on 2018-10-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/002.jpg', upload_to='profile_pic', verbose_name='Profile Pic'),
        ),
    ]
