# Generated by Django 2.1.1 on 2018-10-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_auto_20181013_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='mobile',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic', verbose_name='Profile Pic'),
        ),
    ]
