# Generated by Django 2.1.1 on 2018-10-14 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_auto_20181014_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=40, verbose_name='ID No.')),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], max_length=40, verbose_name='Employment Status')),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contractual', 'Contractual'), ('Probationary', 'Probationary')], max_length=40, verbose_name='Employement Type')),
                ('date_hired', models.DateField(default=django.utils.timezone.now, verbose_name='Date Hired')),
                ('designation', models.CharField(choices=[('Driver', 'Driver'), ('Operator', 'Operator'), ('Site Checker', 'Site Checker'), ('Skilled Laborers', 'Skilled Laborers'), ('Foreman', 'Foreman'), ('Project Engineer', 'Project Engineer'), ('Administrative Clerk', 'Administrative Clerk'), ('Book Keeper', 'Book Keeper'), ('Accountant', 'Accountant'), ('Finance Manager', 'Finance Manager'), ('Purchaser', 'Purchaser'), ('Helper', 'Helper'), ('Project In Charge', 'Project In Charge'), ('Liason', 'Liason'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Dispatcher', 'Dispatcher'), ('Welder', 'Welder'), ('Inventory Analyst', 'Inventory Analyst'), ('Material & Control Officer', 'Material & Control Officer')], max_length=200, verbose_name='Designation')),
                ('branch', models.CharField(blank=True, choices=[('Baguio', 'Baguio'), ('Bontoc', 'Bontoc'), ('Tagaytay', 'Tagaytay')], max_length=200, verbose_name='Branch')),
                ('project_site', models.CharField(blank=True, choices=[('BMH', 'Bontoc Municipal Hall'), ('Contractual', 'Contractual'), ('Probationary', 'Probationary')], max_length=200, verbose_name='Project Site')),
                ('end_probation', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='End of Probation')),
                ('base_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='workforce.BasicProfile')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profile',
            },
        ),
    ]
