# Generated by Django 2.1.1 on 2018-10-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0006_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('designation', models.CharField(max_length=200, verbose_name='Designation')),
                ('start_year', models.DateField(verbose_name='Start Year')),
                ('end_year', models.DateField(verbose_name='End Year')),
                ('work_description', models.CharField(max_length=1000, verbose_name='Work Description')),
                ('supervisor', models.CharField(max_length=200, verbose_name='Immediate Supervisor')),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Mobile No.')),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='workforce.BasicProfile')),
            ],
            options={
                'verbose_name': 'Work History',
                'verbose_name_plural': 'Work Hisotry',
            },
        ),
    ]
