# Generated by Django 2.1.1 on 2018-10-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_workhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=40, verbose_name='Project Code')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Project Site',
                'verbose_name_plural': 'Project Site',
            },
        ),
    ]
