# Generated by Django 2.1.1 on 2018-10-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0008_projectsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='project_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='workforce.ProjectSite'),
        ),
    ]
