# Generated by Django 2.1.1 on 2018-10-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_auto_20181015_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='contact_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Mobile No.'),
        ),
        migrations.AlterField(
            model_name='family',
            name='relation',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sibling', 'Sibling'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Wife', 'Wife')], max_length=200, verbose_name='Relation'),
        ),
    ]
