# Generated by Django 2.1.1 on 2018-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_auto_20181015_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='contact_no',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='Mobile No.'),
        ),
    ]
