# Generated by Django 2.1.1 on 2018-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0013_auto_20181025_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resigned', 'Resigned'), ('On Travel', 'On Travel'), ('On Leave', 'On Leave'), ('Active', 'Active'), ('Absent', 'Absent'), ('AWOL', 'AWOL')], max_length=40, verbose_name='Employment Status'),
        ),
    ]
