# Generated by Django 2.1.1 on 2018-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0015_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned')], max_length=40, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_from',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateTimeField(verbose_name='Start End'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Birthday Leave', 'Birthday Leave'), ('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Vacation Leave', 'Vacation Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Paternity Leave', 'Paternity Leave'), ('Maternity Leave', 'Maternity Leave')], max_length=200, verbose_name='Status'),
        ),
    ]
