# Generated by Django 2.1.1 on 2018-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0016_auto_20181110_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
    ]
