# Generated by Django 2.1.1 on 2018-11-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0017_auto_20181110_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(choices=[('Driver A', 'Driver A'), ('Driver B', 'Driver B'), ('Driver C', 'Driver C'), ('Operator A', 'Operator A'), ('Operator B', 'Operator B'), ('Operator C', 'Operator C'), ('Site Checker', 'Site Checker'), ('Skilled Laborers', 'Skilled Laborers'), ('Foreman', 'Foreman'), ('Project Engineer', 'Project Engineer'), ('Office Engineer', 'Office Engineer'), ('Administrative Clerk', 'Administrative Clerk'), ('Book Keeper', 'Book Keeper'), ('Accountant', 'Accountant'), ('Finance Manager', 'Finance Manager'), ('Purchaser', 'Purchaser'), ('Helper 1', 'Helper 1'), ('Helper 2', 'Helper 2'), ('Helper 3', 'Helper 3'), ('Project In Charge', 'Project In Charge'), ('Liason', 'Liason'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Dispatcher', 'Dispatcher'), ('Welder', 'Welder'), ('Inventory Analyst', 'Inventory Analyst'), ('Materials & Control Officer', 'Materials & Control Officer'), ('Administrative Site Supervisor', 'Administrative Site Supervisor'), ('Administrative Manager', 'Administrative Manager'), ('Assistant Equipment Manager', 'Assistant Equipment Manager'), ('Assistant Equipment Manager', 'Assistant Equipment Manager'), ('Cashier', 'Cashier'), ('Senior Mechanic', 'Senior Mechanic'), ('Chief Mechanic', 'Chief Mechanic'), ('Junior Mechanic', 'Junior Mechanic'), ('Consultant', 'Consultant'), ('Cook', 'Cook'), ('Equipment Clerk', 'Equipment Clerk'), ('Office Clerk', 'Office Clerk'), ('Equipment Manager', 'Equipment Manager'), ('Equipment Supervisor', 'Equipment Supervisor'), ('General Manager', 'General Manager'), ('Geodetic Engineer', 'Geodetic Engineer'), ('IT Junior Programer', 'IT Junior Programer'), ('Laborer', 'Laborer'), ('Liason', 'Liason'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Safety Officer', 'Safety Officer'), ('Security Guard', 'Security Guard'), ('Technical Engineer', 'Technical Engineer'), ('Utility', 'Utility'), ('Operations Manager', 'Operations Manager')], max_length=200, verbose_name='Designation'),
        ),
    ]
