# Generated by Django 2.1.1 on 2018-12-20 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0019_filedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
    ]
