# Generated by Django 2.1.1 on 2018-12-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0020_auto_20181220_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicprofile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth Place'),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='current_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Current Address'),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='height',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='basicprofile',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='home_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Home Address'),
        ),
    ]
