# Generated by Django 2.1.1 on 2019-01-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0023_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Birthday Leave', 'Birthday Leave'), ('Sick Leave', 'Sick Leave'), ('Emergency Leave', 'Emergency Leave'), ('Vacation Leave', 'Vacation Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Paternity Leave', 'Paternity Leave'), ('Maternity Leave', 'Maternity Leave')], max_length=200, verbose_name='Leave'),
        ),
    ]
