# Generated by Django 2.1.1 on 2019-01-22 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0024_auto_20190122_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='base_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_record', to='workforce.BasicProfile'),
        ),
    ]
