# Generated by Django 2.1.1 on 2019-02-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0025_auto_20190122_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='eds',
            field=models.FileField(blank=True, default='', upload_to='eds_files', verbose_name='Employment Data Sheet'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='birthplace',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='current_address',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Current Address'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='mobile',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Mobile No.'),
        ),
    ]
