# Generated by Django 2.1.1 on 2019-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0026_auto_20190202_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='referral',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Referral'),
        ),
    ]
