# Generated by Django 2.1.1 on 2019-02-02 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0027_auto_20190202_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200, verbose_name='Title')),
                ('document_type', models.CharField(choices=[('Memo', 'Memo'), ('Warning', 'Warning'), ('Notice to Explain', 'Notice to Explain')], max_length=200, verbose_name='Document Type')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued')),
                ('expiry_date', models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date')),
                ('doc_file', models.FileField(blank=True, default='', upload_to='memo_files', verbose_name='Employment Data Sheet')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
