# Generated by Django 2.1.1 on 2019-02-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0028_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='base_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_record', to='workforce.BasicProfile'),
            preserve_default=False,
        ),
    ]
