# Generated by Django 2.1.1 on 2019-02-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0029_attachment_base_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(blank=True, default='', upload_to='memo_files', verbose_name='Document'),
        ),
    ]
