# Generated by Django 2.1.1 on 2019-02-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0031_auto_20190202_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='eds',
            field=models.FileField(blank=True, default='profile_pic/default.png', upload_to='eds_files', verbose_name='Employment Data Sheet'),
        ),
    ]
