# Generated by Django 2.1.1 on 2019-02-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0034_auto_20190207_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Weight'),
        ),
    ]
