# Generated by Django 2.1.1 on 2019-02-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0035_auto_20190208_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(blank=True, default='profile_pic/default.png', upload_to='memo_files', verbose_name='Document'),
        ),
    ]
