# Generated by Django 2.1.1 on 2019-02-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0037_auto_20190208_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='doc_file',
            field=models.FileField(blank=True, default='profile_pic/default.png', null=True, upload_to='memo_files', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='doc_image',
            field=models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='doc_files', verbose_name='Scanned Document'),
        ),
    ]
