# Generated by Django 2.1.1 on 2019-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0039_auto_20190208_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='eds',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='document_type',
            field=models.CharField(choices=[('Memo', 'Memo'), ('Warning', 'Warning'), ('Notice to Explain', 'Notice to Explain'), ('Certificate', 'Certificate'), ('Performance Evaluation', 'Performance Evaluation'), ('EDS', 'EDS')], max_length=200, verbose_name='Document Type'),
        ),
    ]
