# Generated by Django 2.1.1 on 2019-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0040_auto_20190208_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='remarks',
            field=models.CharField(max_length=500, verbose_name='Remarks'),
        ),
    ]
