# Generated by Django 2.1.1 on 2019-02-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0041_auto_20190214_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhistory',
            name='end_year',
            field=models.DateField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='start_year',
            field=models.DateField(blank=True, null=True, verbose_name='Start Year'),
        ),
    ]
