# Generated by Django 2.1.1 on 2019-02-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0043_auto_20190216_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhistory',
            options={'verbose_name': 'Work History', 'verbose_name_plural': 'Work History'},
        ),
    ]
