# Generated by Django 2.1.1 on 2019-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0044_auto_20190216_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='Lon'),
        ),
    ]
