# Generated by Django 2.1.1 on 2019-02-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0045_auto_20190218_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document_type',
            field=models.CharField(choices=[('Memo', 'Memo'), ('Warning', 'Warning'), ('Notice to Explain', 'Notice to Explain'), ('Certificate', 'Certificate'), ('Performance Evaluation', 'Performance Evaluation'), ('EDS', 'EDS'), ('License', 'License'), ('Others', 'Others')], max_length=200, verbose_name='Document Type'),
        ),
    ]
