# Generated by Django 2.1.1 on 2019-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0046_auto_20190218_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='tots_days',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=20, verbose_name='Tots'),
        ),
    ]
