# Generated by Django 2.1.1 on 2019-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0047_leave_tots_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outsider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('details', models.TextField(verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Outsider',
                'verbose_name_plural': 'Outsiders',
            },
        ),
        migrations.AlterField(
            model_name='leave',
            name='tots_days',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Total Days'),
        ),
    ]
