# Generated by Django 2.1.1 on 2019-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0048_auto_20190223_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval',
            field=models.CharField(choices=[('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('For Approval', 'For Approval'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, verbose_name='Status'),
        ),
    ]
