# Generated by Django 2.1.1 on 2019-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0050_leave_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='tots_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Total Days'),
        ),
    ]
