# Generated by Django 2.1.1 on 2019-03-22 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0051_auto_20190318_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date:')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount')),
                ('detail', models.CharField(max_length=200, verbose_name='Detail')),
                ('doc_file', models.FileField(blank=True, default=' ', upload_to='loan_files', verbose_name='Form')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('base_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_record', to='workforce.BasicProfile')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date:')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount')),
                ('detail', models.CharField(max_length=200, verbose_name='Detail')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('base_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment', to='workforce.Loans')),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
            },
        ),
    ]
