# Generated by Django 2.1.1 on 2019-03-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0052_loans_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by_loan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('For Approval', 'For Approval'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, verbose_name='Status'),
        ),
    ]
