# Generated by Django 2.1.1 on 2019-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0053_auto_20190323_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='cluster',
            field=models.CharField(blank=True, choices=[('Baguio', 'Baguio'), ('Bontoc', 'Bontoc'), ('Tagaytay', 'Tagaytay')], max_length=200, verbose_name='Project Area'),
        ),
    ]
