# Generated by Django 2.1.1 on 2019-06-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0054_projectsite_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsite',
            old_name='cluster',
            new_name='branch',
        ),
    ]
