# Generated by Django 2.1.1 on 2019-08-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0060_auto_20190802_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='separation',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Separation'),
        ),
    ]
