# Generated by Django 2.1.1 on 2019-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0061_employeeprofile_separation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Height(m)'),
        ),
        migrations.AlterField(
            model_name='basicprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Weight(kg)'),
        ),
    ]
