# Generated by Django 2.1.1 on 2019-09-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0063_auto_20190908_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='project_status',
            field=models.CharField(choices=[('For Bidding', 'For Bidding'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed')], default='Completed', max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectsite',
            name='project_type',
            field=models.CharField(choices=[('Office', 'Office'), ('Project', 'Project'), ('Warehouse', 'Warehouse')], default='Project', max_length=200, verbose_name='Type'),
        ),
    ]
