# Generated by Django 2.1.1 on 2020-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0064_auto_20190910_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedocument',
            name='status',
            field=models.CharField(choices=[('Gathering Documents', 'Gathering Documents'), ('Processing', 'Processing'), ('Renewed', 'Renewed')], default='', max_length=50, verbose_name='Status'),
        ),
    ]
