# Generated by Django 2.1.1 on 2020-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0067_auto_20200212_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateField(verbose_name='End Date'),
        ),
    ]
