# Generated by Django 2.1.1 on 2020-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0068_auto_20200214_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_from',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
