# Generated by Django 2.1.1 on 2020-02-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0070_auto_20200217_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='status',
            field=models.CharField(choices=[('Documents', 'Documents'), ('Processing', 'Processing'), ('Renewed', 'Renewed')], default='Renewed', max_length=50, verbose_name='Status'),
        ),
    ]
