# Generated by Django 2.1.1 on 2020-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0072_employeeprofile_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsite',
            name='project_type',
            field=models.CharField(choices=[('Office', 'Office'), ('Project', 'Project'), ('Warehouse', 'Warehouse'), ('Project Main', 'Project Main')], default='Project', max_length=200, verbose_name='Type'),
        ),
    ]
