# Generated by Django 2.1.1 on 2020-09-20 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0074_auto_20200615_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('boss', models.CharField(max_length=200, verbose_name='Leader')),
                ('remarks', models.TextField(default='', max_length=200, verbose_name='Remarks')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Subcon Group',
                'verbose_name_plural': 'Subcon Groups',
            },
        ),
    ]
