# Generated by Django 2.1.1 on 2020-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0075_subcon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcon',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Completed', max_length=200, verbose_name='Status'),
        ),
    ]
