# Generated by Django 2.1.15 on 2021-03-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0076_subcon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcon',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcon_site', to='workforce.ProjectSite'),
        ),
    ]
