# Generated by Django 2.1.15 on 2021-04-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0081_auto_20210413_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('AWOL', 'AWOL'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, verbose_name='Status (Supervisor)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_supervisor', to='workforce.BasicProfile', verbose_name='Approved by (Supervisor)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='tots_days',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=20, null=True, verbose_name='Total Days'),
        ),
    ]
