# Generated by Django 2.1.15 on 2021-04-15 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0082_auto_20210413_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_super',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('AWOL', 'AWOL'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, verbose_name='Status (Supervisor)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved_by_super',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by_super', to='workforce.BasicProfile', verbose_name='Approved by (Supervisor)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='date_approved',
            field=models.DateField(blank=True, null=True, verbose_name='Date Approved (Admin)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='date_approved_super',
            field=models.DateField(blank=True, null=True, verbose_name='Date Approved (Supervisor)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approval',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('AWOL', 'AWOL'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, verbose_name='Status (Admin)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to='workforce.BasicProfile', verbose_name='Approved by (Admin)'),
        ),
    ]
