# Generated by Django 2.1.15 on 2021-04-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0083_auto_20210415_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval_super',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='For Approval', max_length=200, verbose_name='Status (Supervisor)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=500, verbose_name='Remarks'),
        ),
    ]
