# Generated by Django 2.1.15 on 2021-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0084_auto_20210415_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval',
            field=models.CharField(blank=True, choices=[('For Approval', 'For Approval'), ('Approved w/ Pay', 'Approved w/ Pay'), ('Approved w/o Pay', 'Approved w/o Pay'), ('AWOL', 'AWOL'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='For Approval', max_length=200, null=True, verbose_name='Status (Admin)'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='approval_super',
            field=models.CharField(blank=True, choices=[('For Approval', 'For Approval'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='For Approval', max_length=200, null=True, verbose_name='Status (Supervisor)'),
        ),
    ]
