# Generated by Django 2.1.15 on 2021-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0085_auto_20210415_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks (Admin)'),
        ),
        migrations.AddField(
            model_name='leave',
            name='remarks_super',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks (Supervisor)'),
        ),
    ]
