# Generated by Django 2.1.1 on 2019-09-03 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0062_auto_20190815_2012'),
        ('fleet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('reading', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount/Liters')),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by', to='workforce.BasicProfile')),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('max_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Maximum Capacity/Liters')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_site', to='workforce.ProjectSite')),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('trans_type', models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing'), ('Transfer', 'Transfer')], max_length=200, verbose_name='Transaction')),
                ('fwf', models.CharField(default=0, max_length=50, verbose_name='FWF No.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount/Liters')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Unit Price')),
                ('attachment', models.ImageField(default='profile_pic/default.png', upload_to='fuel_forms', verbose_name='Attach Form')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('smr', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='SMR')),
                ('kmr', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='KMR')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_by', to='workforce.BasicProfile')),
                ('project_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_project_site', to='workforce.ProjectSite')),
                ('tank_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_tank_site', to='fuel.Tank')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_unit', to='fleet.UnitProfile')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='reading',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank', to='fuel.Tank'),
        ),
    ]
