# Generated by Django 2.1.1 on 2019-11-25 20:40

from django.db import migrations, models
import fuel.models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='attachment',
            field=models.ImageField(upload_to='fuel_forms', validators=[fuel.models.validate_upload_size], verbose_name='Attach Form'),
        ),
    ]
