# Generated by Django 2.1.1 on 2019-09-06 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='base_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidation', to='accounting.CashBudget', verbose_name='Cash Request Slip No. (CRS No.)'),
        ),
        migrations.AlterField(
            model_name='liquidation',
            name='trans_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date (Actual):'),
        ),
    ]
