# Generated by Django 2.1.1 on 2020-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20191124_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbudget',
            name='doc_file',
            field=models.FileField(blank=True, default='', upload_to='cf_files', verbose_name='Form'),
        ),
    ]
