# Generated by Django 2.1.1 on 2020-02-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20200205_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbudget',
            name='form_no',
            field=models.CharField(max_length=20, verbose_name='Form No.'),
        ),
    ]
