# Generated by Django 2.1.1 on 2020-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20200305_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('Construction Materials', 'Construction Materials'), ('Spare Parts', 'Spare Parts'), ('Oil & Lubricants', 'Oil & Lubricants'), ('PPE', 'PPE'), ('Tools & Machineries', 'Tools & Machineries'), ('Office Supply', 'Office Supply'), ('Food Supply', 'Food Supply'), ('Fuel', 'Fuel'), ('Kitchen Utensils', 'Kitchen Utensils'), ('Aggregates', 'Aggregates')], max_length=200, verbose_name='Category'),
        ),
    ]
