# Generated by Django 2.1.1 on 2020-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_orderrequest_form_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='jo_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='JO No'),
        ),
    ]
