# Generated by Django 2.1.1 on 2020-07-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20200622_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('For Approval', 'For Approval'), ('On-Process', 'On-Process'), ('Purchased', 'Purchased'), ('Canceled', 'Canceled'), ('Invalid', 'Invalid')], default='For Approval', max_length=200, verbose_name='Status'),
        ),
    ]
