# Generated by Django 2.1.1 on 2020-08-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0074_auto_20200615_1144'),
        ('accounting', '0013_auto_20200719_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbudget',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cb_given_by', to='workforce.BasicProfile'),
        ),
    ]
