# Generated by Django 2.1.1 on 2020-08-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_cashbudget_given_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbudget',
            name='given_by',
        ),
    ]
