# Generated by Django 2.1.1 on 2020-08-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_remove_cashbudget_given_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
    ]
