# Generated by Django 2.1.1 on 2020-09-15 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0074_auto_20200615_1144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0016_auto_20200816_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date (Actual):')),
                ('entry_type', models.CharField(choices=[('Receipts', 'Receipts'), ('Disbursements', 'Disbursements')], max_length=50, verbose_name='Type')),
                ('form_no', models.CharField(max_length=50, verbose_name='Form No.')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Credit')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('account_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_code', to='accounting.ItemCode')),
                ('project_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_project_site', to='workforce.ProjectSite')),
                ('transaction_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entry',
            },
        ),
    ]
