# Generated by Django 2.1.1 on 2020-09-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20200917_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Unliquidated', 'Unliquidated'), ('Liquidated', 'Liquidated')], default='N/A', max_length=200, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Adjustment', 'Adjustment'), ('Credit', 'Credit')], default='Debit', max_length=200, verbose_name='Type'),
        ),
    ]
