# Generated by Django 2.1.1 on 2020-09-18 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20200917_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='incoming_vat',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Vat'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(default='Test', verbose_name='Remarks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_supplier', to='accounting.Supplier'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vat',
            field=models.BooleanField(default=False, verbose_name='Vatable?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vatable_sales',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Vatable Sales'),
            preserve_default=False,
        ),
    ]
