# Generated by Django 2.1.1 on 2020-09-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20200918_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_by',
        ),
    ]
