# Generated by Django 2.1.1 on 2020-09-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0075_subcon'),
        ('accounting', '0027_auto_20200918_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='subcon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcon', to='workforce.Subcon'),
        ),
    ]
