# Generated by Django 2.1.1 on 2020-09-21 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_entry_subcon'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_item', to='accounting.Item'),
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='entry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_supplier', to='accounting.Supplier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='base_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_entry', to='accounting.Entry', verbose_name='Ref. No.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='detail',
            field=models.CharField(max_length=200, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Trans. Date (Actual):'),
        ),
    ]
