# Generated by Django 2.1.1 on 2020-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20200921_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Non-Cash', 'Non-Cash'), ('Receipts', 'Receipts'), ('Disbursements', 'Disbursements')], max_length=50, verbose_name='Type'),
        ),
    ]
