# Generated by Django 2.1.1 on 2020-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_auto_20200921_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Non-Cash', 'Non-Cash'), ('Receipts', 'Receipts'), ('Disbursements', 'Disbursements'), ('Liquidation', 'Liquidation')], default='Liquidation', max_length=50, verbose_name='Type'),
        ),
    ]
