# Generated by Django 2.1.1 on 2020-09-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20200921_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='base_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='base_por',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_by',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
