# Generated by Django 2.1.1 on 2020-09-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_fundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
