# Generated by Django 2.1.1 on 2020-09-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_auto_20200923_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tin',
            field=models.CharField(default=0, max_length=200, verbose_name='TIN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Non-Cash', 'Non-Cash'), ('Receipts', 'Receipts'), ('Disbursements', 'Disbursements')], default='Non-Cash', max_length=50, verbose_name='Type'),
        ),
    ]
