# Generated by Django 2.1.1 on 2020-09-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_auto_20200924_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='credit',
        ),
    ]
