# Generated by Django 2.1.1 on 2020-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_remove_entry_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='utang',
            field=models.BooleanField(default=False, verbose_name='Credit?'),
        ),
    ]
