# Generated by Django 2.1.1 on 2020-09-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_entry_utang'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='base_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_por', to='accounting.OrderRequest', verbose_name='POR Trans #'),
        ),
    ]
