# Generated by Django 2.1.1 on 2020-09-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_entry_base_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
    ]
