# Generated by Django 2.1.1 on 2020-09-25 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0044_auto_20200924_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='request_from',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='request_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
