# Generated by Django 2.1.1 on 2020-09-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_auto_20200925_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_credit',
            field=models.BooleanField(default=False, verbose_name='Credit?'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_debit',
            field=models.BooleanField(default=False, verbose_name='Debit?'),
        ),
    ]
