# Generated by Django 2.1.1 on 2020-09-29 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0046_auto_20200928_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='por_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='por_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
