# Generated by Django 2.1.1 on 2020-09-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_auto_20200929_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='today',
            field=models.BooleanField(default=False, verbose_name='Today?'),
        ),
    ]
