# Generated by Django 2.1.1 on 2020-10-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workforce', '0075_subcon'),
        ('accounting', '0048_orderrequest_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubconBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(default=django.utils.timezone.now, verbose_name='Transaction Date (Actual):')),
                ('status_ops', models.CharField(choices=[('Open', 'Open'), ('For-Review', 'For-Reveiw'), ('Closed', 'Closed')], default='Open', max_length=200, verbose_name='Status')),
                ('file_ops', models.FileField(blank=True, default='', upload_to='billing_files', verbose_name='Attachment')),
                ('remarks_ops', models.TextField(blank=True, verbose_name='Remarks')),
                ('status_acc', models.CharField(choices=[('Open', 'Open'), ('For-Review', 'For-Reveiw'), ('Closed', 'Closed')], default='Open', max_length=200, verbose_name='Status')),
                ('file_acc', models.FileField(blank=True, default='', upload_to='billing_files', verbose_name='Attachment')),
                ('remarks_acc', models.TextField(blank=True, verbose_name='Remarks')),
                ('status_wh', models.CharField(choices=[('Open', 'Open'), ('For-Review', 'For-Reveiw'), ('Closed', 'Closed')], default='Open', max_length=200, verbose_name='Status')),
                ('file_wh', models.FileField(blank=True, default='', upload_to='billing_files', verbose_name='Attachment')),
                ('remarks_wh', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_project_site', to='workforce.ProjectSite')),
                ('request_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_request_by', to=settings.AUTH_USER_MODEL)),
                ('subcon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_subcon', to='workforce.Subcon')),
            ],
            options={
                'verbose_name': 'Subcon Billing',
                'verbose_name_plural': 'Subcon Billings',
            },
        ),
    ]
