# Generated by Django 2.1.1 on 2020-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_subconbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='subconbilling',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Amount'),
        ),
    ]
