# Generated by Django 2.1.1 on 2021-02-11 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_auto_20210211_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
