# Generated by Django 2.1.1 on 2021-02-11 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_orderrequest_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='purchased_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
