# Generated by Django 2.1.1 on 2021-02-15 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_orderrequest_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='por_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
