# Generated by Django 2.1.1 on 2021-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0056_auto_20210216_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
